datastore:
  cls: lsst.daf.butler.datastores.fileDatastore.FileDatastore
  root: <butlerRoot>/datastore
  records:
    table: file_datastore_records
  create: true
  templates:
    default: "{run:/}/{datasetType}.{component:?}/{tract:?}/{patch:?}/{band:?}/{subfilter:?}/{physical_filter:?}/{visit.day_obs:?}/{visit:?}/{exposure.day_obs:?}/{exposure:?}/{datasetType}_{component:?}_{tract:?}_{patch:?}_{band:?}_{physical_filter:?}_{visit:?}_{exposure:?}_{detector:?}_{instrument:?}_{skymap:?}_{skypix:?}_{run}"
  formatters: !include formatters.yaml
  composites: !include composites.yaml
